server:
   command: "php bin/console baldinof:roadrunner:worker"

http:
  address: 0.0.0.0:9090
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

  http2:
    h2c: false
    max_concurrent_streams: 128

  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
  response:
    X-Powered-By: "RoadRunner"

status:
  address: localhost:2114

logs:
  mode: development
  output: stdout

reload:
  enabled: true
  interval: 1s
  patterns: [".php", ".yaml"]
  services:
    http:
      dirs: ["."]
      recursive: true
